name: Ask a question
description: |
  If you have any questions, feel free to ask
labels: 'help wanted'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Kobweb!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched the [existing issues](https://github.com/varabyte/kobweb/issues)
        required: true
  - type: textarea
    attributes:
      label: The question
      description: Please explain your question here
      placeholder: |
        How do I use multi-languages support with Kobweb?
    validations:
      required: true